---

apache_vhosts:
  []
  #- {servername: "babelfish.local", documentroot: "/web/babelfish/public/"}
  #- {servername: "cellular.local", documentroot: "/web/cellular/"}
mysql_dbs:
  []
  #- name: babelfish
  #- name: gtcrm